# Generated by Django 3.2.7 on 2021-09-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fbackend.manzanaverde.la%2Fapi%2Fv1%2Fphoto%2F1200x625-&imgrefurl=https%3A%2F%2Fmanzanaverde.la%2Fmexico%2Fmenu-saludable-semanal%2Fpage%2F15%2F&tbnid=i4LWV8nsfF3pZM&vet=12ahUKEwjHhaaPvZbzAhVBf6wKHWg1AxQQMygAegUIARCuAQ..i&docid=4aznRBH1MFUmSM&w=400&h=267&q=placeholder%20food&ved=2ahUKEwjHhaaPvZbzAhVBf6wKHWg1AxQQMygAegUIARCuAQ', max_length=500),
        ),
    ]
