# Generated by Django 3.2.7 on 2021-09-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fmanzanaverde.la%2Fmexico%2Fmenu-saludable-semanal%2Fpage%2F15%2F&psig=AOvVaw0aN8zuzgmc5lUgxn1i8M06&ust=1632536371594000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIiX8ovGlvMCFQAAAAAdAAAAABAL', max_length=500),
        ),
    ]
